spring.application.name=transferpay
spring.datasource.url=jdbc:postgresql://localhost:5432/transferpay
spring.datasource.username=pedrohmoura
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true